version: "3.8"
services:
  rtmp:
    image: streaming-server:latest   # use the image you already built (streaming-server)
    container_name: rtmp-server
    restart: always
    ports:
      - "1935:1935"
      - "8080:80"
    volumes:
      - ./HLS:/mnt/hls
      - ./recordings:/mnt/recordings
      - ./HTML:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  ws:
    build:
      context: ./ws
    container_name: ws-server
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=3000

